os:
- linux
sudo: true
env:
  global:
  - VERBOSE=true
  - OS=linux
  - ARCH=x86_64
install:
- curl -Ss https://api.github.com/repos/getgauge/gauge/releases/latest
- curl -SsLk https://downloads.gauge.org/stable | sh
matrix:
  include:
  - name: one
  - name: two
