os:
- linux
sudo: true
install:
- echo deb https://dl.bintray.com/gauge/gauge-deb nightly main | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get --allow-unauthenticated install gauge
matrix:
  include:
  - name: one
  - name: two
